# Experiment 2: summarize available approaches
Discover completed recordings from metadata and summarize each task independently. Set `tasks=None` for discovery or specify a list. Checkpoint/protocol validation remains strict. Evaluation seeds are not training seeds.

In [1]:
import json, os, sys
from pathlib import Path
import pandas as pd
from IPython.display import display
ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "notebooks/exp2_analysis.py").exists())
sys.path.insert(0, str(ROOT / "notebooks"))
import exp2_analysis as analysis

## Configuration
Choose discovery or an explicit `tasks` list; `task_options` selects per-task checkpoint hashes and display names. Exports are separate per task. Loaded/unloaded cohorts and profiles stay separate. Missing requested tasks raise an error; incomplete recordings are excluded. Ambiguous checkpoints are never auto-selected.

In [2]:
from b1z1_paper_names import DISPLAY_NAMES, LATEX_METHOD_NAMES
# Paper labels differ from implementation ablation numbers; task IDs stay unchanged.
CONFIG = {
    "input_roots": [str(ROOT / "evaluation/exp2")],  # Recursively inspect this experiment folder.
    "task": None,  # Legacy single-task mode uses output_dir directly.
    "tasks": None,  # Or ["b1z1_pact", "b1z1_unifp_original", "b1z1_ppo_pos"].
    "display_names": dict(DISPLAY_NAMES),
    "task_options": {},  # Per task: {"checkpoint_sha256": "...", "display_name": "..."}.
    "checkpoint_sha256": None,
    "expected_seeds": [0, 1, 2],
    "loading": ["loaded", "unloaded"],
    "output_dir": str(ROOT / "analysis/exp2"),  # Batch output: <output_dir>/<task>/.
    "histogram_edges": [i / 100 for i in range(-50, 51)],
    "acceleration_metrics": False,
}
# Optional JSON overrides support unattended execution without editing this notebook.
if os.environ.get("EXP2_ANALYSIS_CONFIG"):
    CONFIG.update(json.loads(os.environ["EXP2_ANALYSIS_CONFIG"]))

In [3]:
from experiment_batch import plan_summaries
plans, inventory = plan_summaries(CONFIG, experiment=2)
display(pd.DataFrame(inventory))  # Tasks, checkpoints, seeds and output destinations.
summaries = {}
for index, settings in enumerate(plans, 1):
    print(f"[{index}/{len(plans)}] {settings['task']}")
    summary = analysis.summarize(settings)  # Preserve strict per-method validation/statistics.
    summaries[settings["task"]] = summary
    display(pd.DataFrame(summary["aggregates"]))
    print("\n".join(summary["diagnostics"]) or "No missing-data diagnostics.")
    print("Exported:", settings["output_dir"])

,task,runs,evaluation_seeds,checkpoints,output_dir
0,b1z1_pact,9,"[0, 1, 2]",[2eaf0240106b78e6423f2d6e310318d72b1da561c1af3...,/home/oyoungquist/Research/Genesis_Development...
1,b1z1_pact_ab10_actor,9,"[0, 1, 2]",[0674cc16b851e629242ea4e83e913014e9d80d35254a9...,/home/oyoungquist/Research/Genesis_Development...
2,b1z1_pact_ab4_coupled_none,9,"[0, 1, 2]",[acf4a8e0819d75a4b7c3884f3bc95965d550037d5d064...,/home/oyoungquist/Research/Genesis_Development...
3,b1z1_pact_ab5_coupled_concat,9,"[0, 1, 2]",[66955da0c81ae8593487ab2feb192a3b8c2e137fe2c81...,/home/oyoungquist/Research/Genesis_Development...
4,b1z1_pact_ab6_position_film,9,"[0, 1, 2]",[128d2859a46a902a141968f607fa04df39ba90658304f...,/home/oyoungquist/Research/Genesis_Development...
5,b1z1_pact_ab8_coupled_film,9,"[0, 1, 2]",[928a3dd041e64b5da76ea9b1120ebd39062ea41a61b38...,/home/oyoungquist/Research/Genesis_Development...
6,b1z1_pact_ab9_representation,9,"[0, 1, 2]",[74bab1b60b92bf9fdfda43dab84c44f0690ad84577d01...,/home/oyoungquist/Research/Genesis_Development...
7,b1z1_ppo_pos,9,"[0, 1, 2]",[5b08e70fb898608e3a152bb39c9dc03a03baf6eade217...,/home/oyoungquist/Research/Genesis_Development...
8,b1z1_unifp_original,9,"[0, 1, 2]",[3950bf33b7112f11a01fbf3f973a87ddf5d34abaf34d0...,/home/oyoungquist/Research/Genesis_Development...

[1/9] b1z1_pact

,profile,loading,metric,unit,mean,sd,contributing_seeds,attempted_trials,contributing_trials
0,pushing,loaded,ee_error_m,m,0.038828,0.000076,3,150,150.0
1,pushing,loaded,planar_velocity_error_m_s,m/s,0.057250,0.000092,3,150,150.0
2,pushing,loaded,yaw_error_rad_s,rad/s,0.068331,0.000597,3,150,150.0
3,pushing,loaded,S_track,fraction,0.970481,0.000354,3,150,150.0
4,pushing,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
5,pushing,loaded,S_track_velocity,fraction,0.989114,0.000718,3,150,150.0
6,pushing,loaded,S_track_manipulation,fraction,0.980210,0.000331,3,150,150.0
7,pushing,loaded,actuator_saturation_pct,%,0.000000,0.000000,3,150,NaN
8,pushing,loaded,position_violation_pct,%,0.000113,0.000195,3,150,NaN
9,pushing,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
10,pushing,loaded,ee_peak_m,m,0.102595,0.000425,3,150,NaN
11,pushing,loaded,ee_iae_m_s,m*s,0.101133,0.000575,3,150,NaN
12,pushing,loaded,recovery_time_s,s,0.176867,0.004706,3,150,NaN
13,pushing,loaded,recovery_fraction,fraction,1.000000,0.000000,3,150,NaN
14,pushing,loaded,recovery_fraction_ee,fraction,1.000000,0.000000,3,150,NaN
15,pushing,loaded,recovery_fraction_velocity,fraction,1.000000,0.000000,3,150,NaN
16,pulling,loaded,ee_error_m,m,0.047744,0.000056,3,150,150.0
17,pulling,loaded,planar_velocity_error_m_s,m/s,0.095194,0.000249,3,150,150.0
18,pulling,loaded,yaw_error_rad_s,rad/s,0.068219,0.000144,3,150,150.0
19,pulling,loaded,S_track,fraction,0.914267,0.001266,3,150,150.0
20,pulling,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
21,pulling,loaded,S_track_velocity,fraction,0.930771,0.001104,3,150,150.0
22,pulling,loaded,S_track_manipulation,fraction,0.977914,0.000155,3,150,150.0
23,pulling,loaded,actuator_saturation_pct,%,0.000000,0.000000,3,150,NaN
24,pulling,loaded,position_violation_pct,%,0.000000,0.000000,3,150,NaN
25,pulling,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
26,pulling,loaded,ee_peak_m,m,0.087644,0.000352,3,150,NaN
27,pulling,loaded,ee_iae_m_s,m*s,0.119428,0.000136,3,150,NaN
28,pulling,loaded,recovery_time_s,s,0.202357,0.023890,3,150,NaN
29,pulling,loaded,recovery_fraction,fraction,0.838333,0.012583,3,150,NaN
30,pulling,loaded,recovery_fraction_ee,fraction,0.991667,0.007638,3,150,NaN
31,pulling,loaded,recovery_fraction_velocity,fraction,0.881667,0.011547,3,150,NaN
32,carrying,loaded,ee_error_m,m,0.034441,0.000041,3,150,150.0
33,carrying,loaded,planar_velocity_error_m_s,m/s,0.062892,0.000223,3,150,150.0
34,carrying,loaded,yaw_error_rad_s,rad/s,0.090117,0.000515,3,150,150.0
35,carrying,loaded,S_track,fraction,0.968690,0.000550,3,150,150.0
36,carrying,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
37,carrying,loaded,S_track_velocity,fraction,0.982214,0.000429,3,150,150.0
38,carrying,loaded,S_track_manipulation,fraction,0.986119,0.000527,3,150,150.0
39,carrying,loaded,actuator_saturation_pct,%,0.000470,0.000309,3,150,NaN
40,carrying,loaded,position_violation_pct,%,0.417331,0.004373,3,150,NaN
41,carrying,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
42,carrying,loaded,ee_peak_m,m,0.104264,0.000779,3,150,NaN
43,carrying,loaded,ee_iae_m_s,m*s,0.090428,0.000401,3,150,NaN
44,carrying,loaded,recovery_time_s,s,0.218110,0.015621,3,150,NaN
45,carrying,loaded,recovery_fraction,fraction,0.995000,0.005000,3,150,NaN
46,carrying,loaded,recovery_fraction_ee,fraction,1.000000,0.000000,3,150,NaN
47,carrying,loaded,recovery_fraction_velocity,fraction,1.000000,0.000000,3,150,NaN

pushing/unloaded: evaluation seeds []; expected [0, 1, 2]
pulling/unloaded: evaluation seeds []; expected [0, 1, 2]
carrying/unloaded: evaluation seeds []; expected [0, 1, 2]
Exported: /home/oyoungquist/Research/Genesis_Development/HCR_Genesis_PACT_Development/analysis/exp2/b1z1_pact
[2/9] b1z1_pact_ab10_actor

,profile,loading,metric,unit,mean,sd,contributing_seeds,attempted_trials,contributing_trials
0,pushing,loaded,ee_error_m,m,0.050029,0.000114,3,150,150.0
1,pushing,loaded,planar_velocity_error_m_s,m/s,0.065208,0.000111,3,150,150.0
2,pushing,loaded,yaw_error_rad_s,rad/s,0.122084,0.000852,3,150,150.0
3,pushing,loaded,S_track,fraction,0.843533,0.003184,3,150,150.0
4,pushing,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
5,pushing,loaded,S_track_velocity,fraction,0.943490,0.002279,3,150,150.0
6,pushing,loaded,S_track_manipulation,fraction,0.876867,0.001888,3,150,150.0
7,pushing,loaded,actuator_saturation_pct,%,0.000000,0.000000,3,150,NaN
8,pushing,loaded,position_violation_pct,%,0.000000,0.000000,3,150,NaN
9,pushing,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
10,pushing,loaded,ee_peak_m,m,0.109121,0.000971,3,150,NaN
11,pushing,loaded,ee_iae_m_s,m*s,0.130298,0.000716,3,150,NaN
12,pushing,loaded,recovery_time_s,s,0.193488,0.022966,3,150,NaN
13,pushing,loaded,recovery_fraction,fraction,0.738333,0.012583,3,150,NaN
14,pushing,loaded,recovery_fraction_ee,fraction,0.760000,0.005000,3,150,NaN
15,pushing,loaded,recovery_fraction_velocity,fraction,0.963333,0.016073,3,150,NaN
16,pulling,loaded,ee_error_m,m,0.041319,0.000017,3,150,150.0
17,pulling,loaded,planar_velocity_error_m_s,m/s,0.093213,0.000266,3,150,150.0
18,pulling,loaded,yaw_error_rad_s,rad/s,0.094370,0.000401,3,150,150.0
19,pulling,loaded,S_track,fraction,0.893071,0.001529,3,150,150.0
20,pulling,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
21,pulling,loaded,S_track_velocity,fraction,0.895252,0.001430,3,150,150.0
22,pulling,loaded,S_track_manipulation,fraction,0.992981,0.000428,3,150,150.0
23,pulling,loaded,actuator_saturation_pct,%,0.000000,0.000000,3,150,NaN
24,pulling,loaded,position_violation_pct,%,0.128246,0.006744,3,150,NaN
25,pulling,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
26,pulling,loaded,ee_peak_m,m,0.082570,0.000626,3,150,NaN
27,pulling,loaded,ee_iae_m_s,m*s,0.101595,0.000265,3,150,NaN
28,pulling,loaded,recovery_time_s,s,0.204936,0.019138,3,150,NaN
29,pulling,loaded,recovery_fraction,fraction,0.705000,0.008660,3,150,NaN
30,pulling,loaded,recovery_fraction_ee,fraction,1.000000,0.000000,3,150,NaN
31,pulling,loaded,recovery_fraction_velocity,fraction,0.710000,0.013229,3,150,NaN
32,carrying,loaded,ee_error_m,m,0.039414,0.000159,3,150,150.0
33,carrying,loaded,planar_velocity_error_m_s,m/s,0.062009,0.000351,3,150,150.0
34,carrying,loaded,yaw_error_rad_s,rad/s,0.106810,0.000823,3,150,150.0
35,carrying,loaded,S_track,fraction,0.929314,0.001085,3,150,150.0
36,carrying,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
37,carrying,loaded,S_track_velocity,fraction,0.944205,0.001109,3,150,150.0
38,carrying,loaded,S_track_manipulation,fraction,0.980138,0.000621,3,150,150.0
39,carrying,loaded,actuator_saturation_pct,%,0.000025,0.000043,3,150,NaN
40,carrying,loaded,position_violation_pct,%,0.734956,0.010310,3,150,NaN
41,carrying,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
42,carrying,loaded,ee_peak_m,m,0.106298,0.001394,3,150,NaN
43,carrying,loaded,ee_iae_m_s,m*s,0.099661,0.000429,3,150,NaN
44,carrying,loaded,recovery_time_s,s,0.365088,0.014679,3,150,NaN
45,carrying,loaded,recovery_fraction,fraction,0.955000,0.017321,3,150,NaN
46,carrying,loaded,recovery_fraction_ee,fraction,1.000000,0.000000,3,150,NaN
47,carrying,loaded,recovery_fraction_velocity,fraction,0.980000,0.005000,3,150,NaN

pushing/unloaded: evaluation seeds []; expected [0, 1, 2]
pulling/unloaded: evaluation seeds []; expected [0, 1, 2]
carrying/unloaded: evaluation seeds []; expected [0, 1, 2]
Exported: /home/oyoungquist/Research/Genesis_Development/HCR_Genesis_PACT_Development/analysis/exp2/b1z1_pact_ab10_actor
[3/9] b1z1_pact_ab4_coupled_none

,profile,loading,metric,unit,mean,sd,contributing_seeds,attempted_trials,contributing_trials
0,pushing,loaded,ee_error_m,m,0.051401,0.000111,3,150,150.0
1,pushing,loaded,planar_velocity_error_m_s,m/s,0.057559,0.000075,3,150,150.0
2,pushing,loaded,yaw_error_rad_s,rad/s,0.068147,0.000078,3,150,150.0
3,pushing,loaded,S_track,fraction,0.855495,0.001177,3,150,150.0
4,pushing,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
5,pushing,loaded,S_track_velocity,fraction,0.989781,0.000194,3,150,150.0
6,pushing,loaded,S_track_manipulation,fraction,0.861900,0.001276,3,150,150.0
7,pushing,loaded,actuator_saturation_pct,%,0.000000,0.000000,3,150,NaN
8,pushing,loaded,position_violation_pct,%,0.000000,0.000000,3,150,NaN
9,pushing,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
10,pushing,loaded,ee_peak_m,m,0.110844,0.000772,3,150,NaN
11,pushing,loaded,ee_iae_m_s,m*s,0.116820,0.000364,3,150,NaN
12,pushing,loaded,recovery_time_s,s,0.187140,0.011264,3,150,NaN
13,pushing,loaded,recovery_fraction,fraction,0.753333,0.005774,3,150,NaN
14,pushing,loaded,recovery_fraction_ee,fraction,0.753333,0.005774,3,150,NaN
15,pushing,loaded,recovery_fraction_velocity,fraction,1.000000,0.000000,3,150,NaN
16,pulling,loaded,ee_error_m,m,0.076390,0.000050,3,150,150.0
17,pulling,loaded,planar_velocity_error_m_s,m/s,0.076915,0.000134,3,150,150.0
18,pulling,loaded,yaw_error_rad_s,rad/s,0.107771,0.000278,3,150,150.0
19,pulling,loaded,S_track,fraction,0.685690,0.000702,3,150,150.0
20,pulling,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
21,pulling,loaded,S_track_velocity,fraction,0.947105,0.000652,3,150,150.0
22,pulling,loaded,S_track_manipulation,fraction,0.690952,0.000712,3,150,150.0
23,pulling,loaded,actuator_saturation_pct,%,0.000000,0.000000,3,150,NaN
24,pulling,loaded,position_violation_pct,%,0.433841,0.008726,3,150,NaN
25,pulling,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
26,pulling,loaded,ee_peak_m,m,0.117895,0.000174,3,150,NaN
27,pulling,loaded,ee_iae_m_s,m*s,0.185840,0.000137,3,150,NaN
28,pulling,loaded,recovery_time_s,s,0.271333,0.031786,3,150,NaN
29,pulling,loaded,recovery_fraction,fraction,0.500000,0.000000,3,150,NaN
30,pulling,loaded,recovery_fraction_ee,fraction,0.500000,0.000000,3,150,NaN
31,pulling,loaded,recovery_fraction_velocity,fraction,0.925000,0.018028,3,150,NaN
32,carrying,loaded,ee_error_m,m,0.060399,0.000122,3,150,150.0
33,carrying,loaded,planar_velocity_error_m_s,m/s,0.045807,0.000239,3,150,150.0
34,carrying,loaded,yaw_error_rad_s,rad/s,0.072999,0.000491,3,150,150.0
35,carrying,loaded,S_track,fraction,0.796595,0.000363,3,150,150.0
36,carrying,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
37,carrying,loaded,S_track_velocity,fraction,0.988600,0.000076,3,150,150.0
38,carrying,loaded,S_track_manipulation,fraction,0.807348,0.000466,3,150,150.0
39,carrying,loaded,actuator_saturation_pct,%,0.000000,0.000000,3,150,NaN
40,carrying,loaded,position_violation_pct,%,0.081234,0.001473,3,150,NaN
41,carrying,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
42,carrying,loaded,ee_peak_m,m,0.164731,0.000498,3,150,NaN
43,carrying,loaded,ee_iae_m_s,m*s,0.156917,0.000179,3,150,NaN
44,carrying,loaded,recovery_time_s,s,0.206533,0.002491,3,150,NaN
45,carrying,loaded,recovery_fraction,fraction,0.750000,0.000000,3,150,NaN
46,carrying,loaded,recovery_fraction_ee,fraction,0.750000,0.000000,3,150,NaN
47,carrying,loaded,recovery_fraction_velocity,fraction,1.000000,0.000000,3,150,NaN

pushing/unloaded: evaluation seeds []; expected [0, 1, 2]
pulling/unloaded: evaluation seeds []; expected [0, 1, 2]
carrying/unloaded: evaluation seeds []; expected [0, 1, 2]
Exported: /home/oyoungquist/Research/Genesis_Development/HCR_Genesis_PACT_Development/analysis/exp2/b1z1_pact_ab4_coupled_none
[4/9] b1z1_pact_ab5_coupled_concat

,profile,loading,metric,unit,mean,sd,contributing_seeds,attempted_trials,contributing_trials
0,pushing,loaded,ee_error_m,m,0.048131,0.000044,3,150,150.0
1,pushing,loaded,planar_velocity_error_m_s,m/s,0.059734,0.000208,3,150,150.0
2,pushing,loaded,yaw_error_rad_s,rad/s,0.067153,0.000187,3,150,150.0
3,pushing,loaded,S_track,fraction,0.971095,0.000500,3,150,150.0
4,pushing,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
5,pushing,loaded,S_track_velocity,fraction,0.994976,0.000135,3,150,150.0
6,pushing,loaded,S_track_manipulation,fraction,0.975443,0.000446,3,150,150.0
7,pushing,loaded,actuator_saturation_pct,%,0.000000,0.000000,3,150,NaN
8,pushing,loaded,position_violation_pct,%,0.000000,0.000000,3,150,NaN
9,pushing,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
10,pushing,loaded,ee_peak_m,m,0.105130,0.000336,3,150,NaN
11,pushing,loaded,ee_iae_m_s,m*s,0.110723,0.000321,3,150,NaN
12,pushing,loaded,recovery_time_s,s,0.197367,0.005987,3,150,NaN
13,pushing,loaded,recovery_fraction,fraction,1.000000,0.000000,3,150,NaN
14,pushing,loaded,recovery_fraction_ee,fraction,1.000000,0.000000,3,150,NaN
15,pushing,loaded,recovery_fraction_velocity,fraction,1.000000,0.000000,3,150,NaN
16,pulling,loaded,ee_error_m,m,0.060105,0.000086,3,150,150.0
17,pulling,loaded,planar_velocity_error_m_s,m/s,0.071829,0.000216,3,150,150.0
18,pulling,loaded,yaw_error_rad_s,rad/s,0.063972,0.000194,3,150,150.0
19,pulling,loaded,S_track,fraction,0.887157,0.000637,3,150,150.0
20,pulling,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
21,pulling,loaded,S_track_velocity,fraction,0.981043,0.000586,3,150,150.0
22,pulling,loaded,S_track_manipulation,fraction,0.900833,0.000873,3,150,150.0
23,pulling,loaded,actuator_saturation_pct,%,0.000000,0.000000,3,150,NaN
24,pulling,loaded,position_violation_pct,%,0.000006,0.000011,3,150,NaN
25,pulling,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
26,pulling,loaded,ee_peak_m,m,0.103809,0.000778,3,150,NaN
27,pulling,loaded,ee_iae_m_s,m*s,0.139870,0.000458,3,150,NaN
28,pulling,loaded,recovery_time_s,s,0.087164,0.007535,3,150,NaN
29,pulling,loaded,recovery_fraction,fraction,0.755000,0.005000,3,150,NaN
30,pulling,loaded,recovery_fraction_ee,fraction,0.758333,0.007638,3,150,NaN
31,pulling,loaded,recovery_fraction_velocity,fraction,1.000000,0.000000,3,150,NaN
32,carrying,loaded,ee_error_m,m,0.066503,0.000122,3,150,150.0
33,carrying,loaded,planar_velocity_error_m_s,m/s,0.050764,0.000270,3,150,150.0
34,carrying,loaded,yaw_error_rad_s,rad/s,0.070258,0.000121,3,150,150.0
35,carrying,loaded,S_track,fraction,0.798962,0.001716,3,150,150.0
36,carrying,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
37,carrying,loaded,S_track_velocity,fraction,0.994367,0.000385,3,150,150.0
38,carrying,loaded,S_track_manipulation,fraction,0.804305,0.001403,3,150,150.0
39,carrying,loaded,actuator_saturation_pct,%,0.000000,0.000000,3,150,NaN
40,carrying,loaded,position_violation_pct,%,0.000038,0.000065,3,150,NaN
41,carrying,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
42,carrying,loaded,ee_peak_m,m,0.144918,0.000707,3,150,NaN
43,carrying,loaded,ee_iae_m_s,m*s,0.159763,0.000324,3,150,NaN
44,carrying,loaded,recovery_time_s,s,0.287956,0.008544,3,150,NaN
45,carrying,loaded,recovery_fraction,fraction,0.750000,0.000000,3,150,NaN
46,carrying,loaded,recovery_fraction_ee,fraction,0.750000,0.000000,3,150,NaN
47,carrying,loaded,recovery_fraction_velocity,fraction,1.000000,0.000000,3,150,NaN

pushing/unloaded: evaluation seeds []; expected [0, 1, 2]
pulling/unloaded: evaluation seeds []; expected [0, 1, 2]
carrying/unloaded: evaluation seeds []; expected [0, 1, 2]
Exported: /home/oyoungquist/Research/Genesis_Development/HCR_Genesis_PACT_Development/analysis/exp2/b1z1_pact_ab5_coupled_concat
[5/9] b1z1_pact_ab6_position_film

,profile,loading,metric,unit,mean,sd,contributing_seeds,attempted_trials,contributing_trials
0,pushing,loaded,ee_error_m,m,0.060019,0.000093,3,150,150.0
1,pushing,loaded,planar_velocity_error_m_s,m/s,0.061803,0.000209,3,150,150.0
2,pushing,loaded,yaw_error_rad_s,rad/s,0.069970,0.000831,3,150,150.0
3,pushing,loaded,S_track,fraction,0.958538,0.001761,3,150,150.0
4,pushing,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
5,pushing,loaded,S_track_velocity,fraction,0.991400,0.000488,3,150,150.0
6,pushing,loaded,S_track_manipulation,fraction,0.965029,0.001493,3,150,150.0
7,pushing,loaded,actuator_saturation_pct,%,0.000000,0.000000,3,150,NaN
8,pushing,loaded,position_violation_pct,%,0.967337,0.009471,3,150,NaN
9,pushing,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
10,pushing,loaded,ee_peak_m,m,0.102672,0.000661,3,150,NaN
11,pushing,loaded,ee_iae_m_s,m*s,0.114588,0.000366,3,150,NaN
12,pushing,loaded,recovery_time_s,s,0.265433,0.021622,3,150,NaN
13,pushing,loaded,recovery_fraction,fraction,1.000000,0.000000,3,150,NaN
14,pushing,loaded,recovery_fraction_ee,fraction,1.000000,0.000000,3,150,NaN
15,pushing,loaded,recovery_fraction_velocity,fraction,1.000000,0.000000,3,150,NaN
16,pulling,loaded,ee_error_m,m,0.121248,0.000081,3,150,150.0
17,pulling,loaded,planar_velocity_error_m_s,m/s,0.078852,0.000259,3,150,150.0
18,pulling,loaded,yaw_error_rad_s,rad/s,0.092392,0.000197,3,150,150.0
19,pulling,loaded,S_track,fraction,0.399067,0.001137,3,150,150.0
20,pulling,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
21,pulling,loaded,S_track_velocity,fraction,0.947005,0.000854,3,150,150.0
22,pulling,loaded,S_track_manipulation,fraction,0.402671,0.000934,3,150,150.0
23,pulling,loaded,actuator_saturation_pct,%,0.000000,0.000000,3,150,NaN
24,pulling,loaded,position_violation_pct,%,2.131366,0.004829,3,150,NaN
25,pulling,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
26,pulling,loaded,ee_peak_m,m,0.176190,0.001297,3,150,NaN
27,pulling,loaded,ee_iae_m_s,m*s,0.283328,0.000461,3,150,NaN
28,pulling,loaded,recovery_time_s,s,0.237393,0.042249,3,150,NaN
29,pulling,loaded,recovery_fraction,fraction,0.248333,0.002887,3,150,NaN
30,pulling,loaded,recovery_fraction_ee,fraction,0.248333,0.002887,3,150,NaN
31,pulling,loaded,recovery_fraction_velocity,fraction,0.908333,0.015275,3,150,NaN
32,carrying,loaded,ee_error_m,m,0.072176,0.000516,3,150,150.0
33,carrying,loaded,planar_velocity_error_m_s,m/s,0.048186,0.000218,3,150,150.0
34,carrying,loaded,yaw_error_rad_s,rad/s,0.071090,0.000223,3,150,150.0
35,carrying,loaded,S_track,fraction,0.807248,0.004282,3,150,150.0
36,carrying,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
37,carrying,loaded,S_track_velocity,fraction,0.991957,0.000497,3,150,150.0
38,carrying,loaded,S_track_manipulation,fraction,0.813143,0.004136,3,150,150.0
39,carrying,loaded,actuator_saturation_pct,%,0.000000,0.000000,3,150,NaN
40,carrying,loaded,position_violation_pct,%,0.165401,0.009258,3,150,NaN
41,carrying,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
42,carrying,loaded,ee_peak_m,m,0.165324,0.000572,3,150,NaN
43,carrying,loaded,ee_iae_m_s,m*s,0.185688,0.000995,3,150,NaN
44,carrying,loaded,recovery_time_s,s,0.392626,0.016860,3,150,NaN
45,carrying,loaded,recovery_fraction,fraction,0.668333,0.016073,3,150,NaN
46,carrying,loaded,recovery_fraction_ee,fraction,0.670000,0.017321,3,150,NaN
47,carrying,loaded,recovery_fraction_velocity,fraction,1.000000,0.000000,3,150,NaN

pushing/unloaded: evaluation seeds []; expected [0, 1, 2]
pulling/unloaded: evaluation seeds []; expected [0, 1, 2]
carrying/unloaded: evaluation seeds []; expected [0, 1, 2]
Exported: /home/oyoungquist/Research/Genesis_Development/HCR_Genesis_PACT_Development/analysis/exp2/b1z1_pact_ab6_position_film
[6/9] b1z1_pact_ab8_coupled_film

,profile,loading,metric,unit,mean,sd,contributing_seeds,attempted_trials,contributing_trials
0,pushing,loaded,ee_error_m,m,0.053733,0.000129,3,150,150.0
1,pushing,loaded,planar_velocity_error_m_s,m/s,0.078226,0.000069,3,150,150.0
2,pushing,loaded,yaw_error_rad_s,rad/s,0.078281,0.000369,3,150,150.0
3,pushing,loaded,S_track,fraction,0.886214,0.002105,3,150,150.0
4,pushing,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
5,pushing,loaded,S_track_velocity,fraction,0.981733,0.000740,3,150,150.0
6,pushing,loaded,S_track_manipulation,fraction,0.892776,0.002488,3,150,150.0
7,pushing,loaded,actuator_saturation_pct,%,0.000000,0.000000,3,150,NaN
8,pushing,loaded,position_violation_pct,%,0.000000,0.000000,3,150,NaN
9,pushing,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
10,pushing,loaded,ee_peak_m,m,0.107194,0.000785,3,150,NaN
11,pushing,loaded,ee_iae_m_s,m*s,0.115234,0.000681,3,150,NaN
12,pushing,loaded,recovery_time_s,s,0.236727,0.019417,3,150,NaN
13,pushing,loaded,recovery_fraction,fraction,0.881667,0.012583,3,150,NaN
14,pushing,loaded,recovery_fraction_ee,fraction,0.906667,0.007638,3,150,NaN
15,pushing,loaded,recovery_fraction_velocity,fraction,0.993333,0.007638,3,150,NaN
16,pulling,loaded,ee_error_m,m,0.086933,0.000263,3,150,150.0
17,pulling,loaded,planar_velocity_error_m_s,m/s,0.090887,0.001031,3,150,150.0
18,pulling,loaded,yaw_error_rad_s,rad/s,0.093385,0.000597,3,150,150.0
19,pulling,loaded,S_track,fraction,0.617567,0.004962,3,150,150.0
20,pulling,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
21,pulling,loaded,S_track_velocity,fraction,0.933200,0.001883,3,150,150.0
22,pulling,loaded,S_track_manipulation,fraction,0.623443,0.005044,3,150,150.0
23,pulling,loaded,actuator_saturation_pct,%,0.000000,0.000000,3,150,NaN
24,pulling,loaded,position_violation_pct,%,0.001936,0.000311,3,150,NaN
25,pulling,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
26,pulling,loaded,ee_peak_m,m,0.132548,0.000579,3,150,NaN
27,pulling,loaded,ee_iae_m_s,m*s,0.208031,0.000503,3,150,NaN
28,pulling,loaded,recovery_time_s,s,0.323110,0.018909,3,150,NaN
29,pulling,loaded,recovery_fraction,fraction,0.463333,0.011547,3,150,NaN
30,pulling,loaded,recovery_fraction_ee,fraction,0.463333,0.011547,3,150,NaN
31,pulling,loaded,recovery_fraction_velocity,fraction,0.878333,0.020817,3,150,NaN
32,carrying,loaded,ee_error_m,m,0.055667,0.000063,3,150,150.0
33,carrying,loaded,planar_velocity_error_m_s,m/s,0.059010,0.000232,3,150,150.0
34,carrying,loaded,yaw_error_rad_s,rad/s,0.066600,0.000270,3,150,150.0
35,carrying,loaded,S_track,fraction,0.834500,0.000329,3,150,150.0
36,carrying,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
37,carrying,loaded,S_track_velocity,fraction,0.992186,0.000480,3,150,150.0
38,carrying,loaded,S_track_manipulation,fraction,0.841252,0.000400,3,150,150.0
39,carrying,loaded,actuator_saturation_pct,%,0.000000,0.000000,3,150,NaN
40,carrying,loaded,position_violation_pct,%,0.000144,0.000128,3,150,NaN
41,carrying,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
42,carrying,loaded,ee_peak_m,m,0.131832,0.000344,3,150,NaN
43,carrying,loaded,ee_iae_m_s,m*s,0.130034,0.000303,3,150,NaN
44,carrying,loaded,recovery_time_s,s,0.264633,0.005996,3,150,NaN
45,carrying,loaded,recovery_fraction,fraction,0.761667,0.002887,3,150,NaN
46,carrying,loaded,recovery_fraction_ee,fraction,0.761667,0.002887,3,150,NaN
47,carrying,loaded,recovery_fraction_velocity,fraction,1.000000,0.000000,3,150,NaN

pushing/unloaded: evaluation seeds []; expected [0, 1, 2]
pulling/unloaded: evaluation seeds []; expected [0, 1, 2]
carrying/unloaded: evaluation seeds []; expected [0, 1, 2]
Exported: /home/oyoungquist/Research/Genesis_Development/HCR_Genesis_PACT_Development/analysis/exp2/b1z1_pact_ab8_coupled_film
[7/9] b1z1_pact_ab9_representation

,profile,loading,metric,unit,mean,sd,contributing_seeds,attempted_trials,contributing_trials
0,pushing,loaded,ee_error_m,m,0.054403,0.000030,3,150,150.0
1,pushing,loaded,planar_velocity_error_m_s,m/s,0.045583,0.000143,3,150,150.0
2,pushing,loaded,yaw_error_rad_s,rad/s,0.073553,0.000552,3,150,150.0
3,pushing,loaded,S_track,fraction,0.819367,0.000167,3,150,150.0
4,pushing,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
5,pushing,loaded,S_track_velocity,fraction,0.992710,0.000385,3,150,150.0
6,pushing,loaded,S_track_manipulation,fraction,0.825838,0.000190,3,150,150.0
7,pushing,loaded,actuator_saturation_pct,%,0.000000,0.000000,3,150,NaN
8,pushing,loaded,position_violation_pct,%,0.000000,0.000000,3,150,NaN
9,pushing,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
10,pushing,loaded,ee_peak_m,m,0.112250,0.000877,3,150,NaN
11,pushing,loaded,ee_iae_m_s,m*s,0.131696,0.000185,3,150,NaN
12,pushing,loaded,recovery_time_s,s,0.219633,0.002923,3,150,NaN
13,pushing,loaded,recovery_fraction,fraction,0.758333,0.007638,3,150,NaN
14,pushing,loaded,recovery_fraction_ee,fraction,0.758333,0.007638,3,150,NaN
15,pushing,loaded,recovery_fraction_velocity,fraction,1.000000,0.000000,3,150,NaN
16,pulling,loaded,ee_error_m,m,0.059721,0.000227,3,150,150.0
17,pulling,loaded,planar_velocity_error_m_s,m/s,0.067474,0.000415,3,150,150.0
18,pulling,loaded,yaw_error_rad_s,rad/s,0.081186,0.000707,3,150,150.0
19,pulling,loaded,S_track,fraction,0.954267,0.001996,3,150,150.0
20,pulling,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
21,pulling,loaded,S_track_velocity,fraction,0.987919,0.000341,3,150,150.0
22,pulling,loaded,S_track_manipulation,fraction,0.965010,0.001723,3,150,150.0
23,pulling,loaded,actuator_saturation_pct,%,0.000000,0.000000,3,150,NaN
24,pulling,loaded,position_violation_pct,%,0.000000,0.000000,3,150,NaN
25,pulling,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
26,pulling,loaded,ee_peak_m,m,0.097721,0.000759,3,150,NaN
27,pulling,loaded,ee_iae_m_s,m*s,0.138889,0.000182,3,150,NaN
28,pulling,loaded,recovery_time_s,s,0.140500,0.012856,3,150,NaN
29,pulling,loaded,recovery_fraction,fraction,1.000000,0.000000,3,150,NaN
30,pulling,loaded,recovery_fraction_ee,fraction,1.000000,0.000000,3,150,NaN
31,pulling,loaded,recovery_fraction_velocity,fraction,1.000000,0.000000,3,150,NaN
32,carrying,loaded,ee_error_m,m,0.055072,0.000167,3,150,150.0
33,carrying,loaded,planar_velocity_error_m_s,m/s,0.049698,0.000044,3,150,150.0
34,carrying,loaded,yaw_error_rad_s,rad/s,0.070868,0.000442,3,150,150.0
35,carrying,loaded,S_track,fraction,0.828810,0.000207,3,150,150.0
36,carrying,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
37,carrying,loaded,S_track_velocity,fraction,0.991162,0.000182,3,150,150.0
38,carrying,loaded,S_track_manipulation,fraction,0.837362,0.000084,3,150,150.0
39,carrying,loaded,actuator_saturation_pct,%,0.000000,0.000000,3,150,NaN
40,carrying,loaded,position_violation_pct,%,0.008177,0.000767,3,150,NaN
41,carrying,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
42,carrying,loaded,ee_peak_m,m,0.123719,0.000837,3,150,NaN
43,carrying,loaded,ee_iae_m_s,m*s,0.139577,0.000501,3,150,NaN
44,carrying,loaded,recovery_time_s,s,0.254667,0.008653,3,150,NaN
45,carrying,loaded,recovery_fraction,fraction,0.750000,0.000000,3,150,NaN
46,carrying,loaded,recovery_fraction_ee,fraction,0.750000,0.000000,3,150,NaN
47,carrying,loaded,recovery_fraction_velocity,fraction,1.000000,0.000000,3,150,NaN

pushing/unloaded: evaluation seeds []; expected [0, 1, 2]
pulling/unloaded: evaluation seeds []; expected [0, 1, 2]
carrying/unloaded: evaluation seeds []; expected [0, 1, 2]
Exported: /home/oyoungquist/Research/Genesis_Development/HCR_Genesis_PACT_Development/analysis/exp2/b1z1_pact_ab9_representation
[8/9] b1z1_ppo_pos

,profile,loading,metric,unit,mean,sd,contributing_seeds,attempted_trials,contributing_trials
0,pushing,loaded,ee_error_m,m,0.050604,0.000025,3,150,150.0
1,pushing,loaded,planar_velocity_error_m_s,m/s,0.070384,0.000132,3,150,150.0
2,pushing,loaded,yaw_error_rad_s,rad/s,0.074120,0.000328,3,150,150.0
3,pushing,loaded,S_track,fraction,0.891310,0.002570,3,150,150.0
4,pushing,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
5,pushing,loaded,S_track_velocity,fraction,0.992419,0.000326,3,150,150.0
6,pushing,loaded,S_track_manipulation,fraction,0.897214,0.002797,3,150,150.0
7,pushing,loaded,actuator_saturation_pct,%,0.000000,0.000000,3,150,NaN
8,pushing,loaded,position_violation_pct,%,0.000000,0.000000,3,150,NaN
9,pushing,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
10,pushing,loaded,ee_peak_m,m,0.098860,0.000319,3,150,NaN
11,pushing,loaded,ee_iae_m_s,m*s,0.112083,0.000149,3,150,NaN
12,pushing,loaded,recovery_time_s,s,0.137489,0.005482,3,150,NaN
13,pushing,loaded,recovery_fraction,fraction,0.985000,0.013229,3,150,NaN
14,pushing,loaded,recovery_fraction_ee,fraction,0.990000,0.008660,3,150,NaN
15,pushing,loaded,recovery_fraction_velocity,fraction,1.000000,0.000000,3,150,NaN
16,pulling,loaded,ee_error_m,m,0.056798,0.000290,3,150,150.0
17,pulling,loaded,planar_velocity_error_m_s,m/s,0.062090,0.000243,3,150,150.0
18,pulling,loaded,yaw_error_rad_s,rad/s,0.108674,0.000429,3,150,150.0
19,pulling,loaded,S_track,fraction,0.955724,0.001195,3,150,150.0
20,pulling,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
21,pulling,loaded,S_track_velocity,fraction,0.972752,0.000360,3,150,150.0
22,pulling,loaded,S_track_manipulation,fraction,0.981690,0.000915,3,150,150.0
23,pulling,loaded,actuator_saturation_pct,%,0.000000,0.000000,3,150,NaN
24,pulling,loaded,position_violation_pct,%,0.000000,0.000000,3,150,NaN
25,pulling,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
26,pulling,loaded,ee_peak_m,m,0.098927,0.000359,3,150,NaN
27,pulling,loaded,ee_iae_m_s,m*s,0.141564,0.000659,3,150,NaN
28,pulling,loaded,recovery_time_s,s,0.274092,0.030241,3,150,NaN
29,pulling,loaded,recovery_fraction,fraction,0.945000,0.013229,3,150,NaN
30,pulling,loaded,recovery_fraction_ee,fraction,1.000000,0.000000,3,150,NaN
31,pulling,loaded,recovery_fraction_velocity,fraction,0.986667,0.002887,3,150,NaN
32,carrying,loaded,ee_error_m,m,0.056528,0.000137,3,150,150.0
33,carrying,loaded,planar_velocity_error_m_s,m/s,0.067932,0.000177,3,150,150.0
34,carrying,loaded,yaw_error_rad_s,rad/s,0.084431,0.000586,3,150,150.0
35,carrying,loaded,S_track,fraction,0.828257,0.001002,3,150,150.0
36,carrying,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
37,carrying,loaded,S_track_velocity,fraction,0.992324,0.000203,3,150,150.0
38,carrying,loaded,S_track_manipulation,fraction,0.833552,0.000802,3,150,150.0
39,carrying,loaded,actuator_saturation_pct,%,0.000000,0.000000,3,150,NaN
40,carrying,loaded,position_violation_pct,%,0.000000,0.000000,3,150,NaN
41,carrying,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
42,carrying,loaded,ee_peak_m,m,0.112836,0.000145,3,150,NaN
43,carrying,loaded,ee_iae_m_s,m*s,0.141929,0.000313,3,150,NaN
44,carrying,loaded,recovery_time_s,s,0.082711,0.011806,3,150,NaN
45,carrying,loaded,recovery_fraction,fraction,0.750000,0.000000,3,150,NaN
46,carrying,loaded,recovery_fraction_ee,fraction,0.750000,0.000000,3,150,NaN
47,carrying,loaded,recovery_fraction_velocity,fraction,1.000000,0.000000,3,150,NaN

pushing/unloaded: evaluation seeds []; expected [0, 1, 2]
pulling/unloaded: evaluation seeds []; expected [0, 1, 2]
carrying/unloaded: evaluation seeds []; expected [0, 1, 2]
Exported: /home/oyoungquist/Research/Genesis_Development/HCR_Genesis_PACT_Development/analysis/exp2/b1z1_ppo_pos
[9/9] b1z1_unifp_original

,profile,loading,metric,unit,mean,sd,contributing_seeds,attempted_trials,contributing_trials
0,pushing,loaded,ee_error_m,m,0.037348,0.000025,3,150,150.0
1,pushing,loaded,planar_velocity_error_m_s,m/s,0.050652,0.000188,3,150,150.0
2,pushing,loaded,yaw_error_rad_s,rad/s,0.108994,0.000315,3,150,150.0
3,pushing,loaded,S_track,fraction,0.925995,0.000756,3,150,150.0
4,pushing,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
5,pushing,loaded,S_track_velocity,fraction,0.954033,0.000642,3,150,150.0
6,pushing,loaded,S_track_manipulation,fraction,0.966681,0.000257,3,150,150.0
7,pushing,loaded,actuator_saturation_pct,%,0.021848,0.000339,3,150,NaN
8,pushing,loaded,position_violation_pct,%,0.000000,0.000000,3,150,NaN
9,pushing,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
10,pushing,loaded,ee_peak_m,m,0.114200,0.000914,3,150,NaN
11,pushing,loaded,ee_iae_m_s,m*s,0.102523,0.000278,3,150,NaN
12,pushing,loaded,recovery_time_s,s,0.455318,0.013931,3,150,NaN
13,pushing,loaded,recovery_fraction,fraction,0.978333,0.005774,3,150,NaN
14,pushing,loaded,recovery_fraction_ee,fraction,1.000000,0.000000,3,150,NaN
15,pushing,loaded,recovery_fraction_velocity,fraction,0.983333,0.002887,3,150,NaN
16,pulling,loaded,ee_error_m,m,0.042563,0.000002,3,150,150.0
17,pulling,loaded,planar_velocity_error_m_s,m/s,0.050690,0.000209,3,150,150.0
18,pulling,loaded,yaw_error_rad_s,rad/s,0.068165,0.000317,3,150,150.0
19,pulling,loaded,S_track,fraction,0.976967,0.000286,3,150,150.0
20,pulling,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
21,pulling,loaded,S_track_velocity,fraction,0.997490,0.000064,3,150,150.0
22,pulling,loaded,S_track_manipulation,fraction,0.979176,0.000265,3,150,150.0
23,pulling,loaded,actuator_saturation_pct,%,0.001886,0.000011,3,150,NaN
24,pulling,loaded,position_violation_pct,%,0.000000,0.000000,3,150,NaN
25,pulling,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
26,pulling,loaded,ee_peak_m,m,0.104163,0.000114,3,150,NaN
27,pulling,loaded,ee_iae_m_s,m*s,0.112132,0.000434,3,150,NaN
28,pulling,loaded,recovery_time_s,s,0.267333,0.002003,3,150,NaN
29,pulling,loaded,recovery_fraction,fraction,1.000000,0.000000,3,150,NaN
30,pulling,loaded,recovery_fraction_ee,fraction,1.000000,0.000000,3,150,NaN
31,pulling,loaded,recovery_fraction_velocity,fraction,1.000000,0.000000,3,150,NaN
32,carrying,loaded,ee_error_m,m,0.044618,0.000103,3,150,150.0
33,carrying,loaded,planar_velocity_error_m_s,m/s,0.044303,0.000052,3,150,150.0
34,carrying,loaded,yaw_error_rad_s,rad/s,0.065145,0.000128,3,150,150.0
35,carrying,loaded,S_track,fraction,0.874919,0.000823,3,150,150.0
36,carrying,loaded,failure_rate,fraction,0.000000,0.000000,3,150,150.0
37,carrying,loaded,S_track_velocity,fraction,0.992943,0.000566,3,150,150.0
38,carrying,loaded,S_track_manipulation,fraction,0.881552,0.000457,3,150,150.0
39,carrying,loaded,actuator_saturation_pct,%,0.022813,0.000110,3,150,NaN
40,carrying,loaded,position_violation_pct,%,0.019925,0.000974,3,150,NaN
41,carrying,loaded,velocity_violation_pct,%,0.000000,0.000000,3,150,NaN
42,carrying,loaded,ee_peak_m,m,0.159885,0.000717,3,150,NaN
43,carrying,loaded,ee_iae_m_s,m*s,0.126296,0.000141,3,150,NaN
44,carrying,loaded,recovery_time_s,s,0.291244,0.005924,3,150,NaN
45,carrying,loaded,recovery_fraction,fraction,0.750000,0.000000,3,150,NaN
46,carrying,loaded,recovery_fraction_ee,fraction,0.750000,0.000000,3,150,NaN
47,carrying,loaded,recovery_fraction_velocity,fraction,1.000000,0.000000,3,150,NaN

pushing/unloaded: evaluation seeds []; expected [0, 1, 2]
pulling/unloaded: evaluation seeds []; expected [0, 1, 2]
carrying/unloaded: evaluation seeds []; expected [0, 1, 2]
Exported: /home/oyoungquist/Research/Genesis_Development/HCR_Genesis_PACT_Development/analysis/exp2/b1z1_unifp_original

## Stages and audit data
The 25 N moving-EE, 45 N, 65 N moving, stop ramp, and 65 N holding phases remain distinct. Unloaded controls use the same stage labels but zero applied load. S_track denominators include prescribed failed tails. Complete response windows alone contribute peak/IAE; failed trials remain unrecovered under the Exp1 convention.

In [4]:
for task, summary in summaries.items():
    print(task)
    display(pd.DataFrame(summary["stage_aggregates"]))
print("Portable summaries, histograms and time_series.csv require no raw recordings for comparison.")

b1z1_pact

,profile,loading,stage,metric,unit,mean,sd,contributing_seeds
0,pushing,loaded,stationary_unloaded,ee_error_m,m,0.024031,0.000128,3
1,pushing,loaded,stationary_unloaded,planar_velocity_error_m_s,m/s,0.036776,0.000568,3
2,pushing,loaded,stationary_unloaded,yaw_error_rad_s,rad/s,0.057167,0.000828,3
3,pushing,loaded,stationary_unloaded,S_track,fraction,0.980089,0.000077,3
4,pushing,loaded,start_ramp,ee_error_m,m,0.023517,0.000430,3
...,...,...,...,...,...,...,...,...
103,carrying,loaded,loaded_stationary,S_track,fraction,0.995627,0.002491,3
104,carrying,loaded,released,ee_error_m,m,0.032131,0.000437,3
105,carrying,loaded,released,planar_velocity_error_m_s,m/s,0.033737,0.000483,3
106,carrying,loaded,released,yaw_error_rad_s,rad/s,0.086005,0.000886,3
107,carrying,loaded,released,S_track,fraction,0.972085,0.001913,3

b1z1_pact_ab10_actor

,profile,loading,stage,metric,unit,mean,sd,contributing_seeds
0,pushing,loaded,stationary_unloaded,ee_error_m,m,0.021376,0.000074,3
1,pushing,loaded,stationary_unloaded,planar_velocity_error_m_s,m/s,0.036741,0.000449,3
2,pushing,loaded,stationary_unloaded,yaw_error_rad_s,rad/s,0.059918,0.000773,3
3,pushing,loaded,stationary_unloaded,S_track,fraction,0.979911,0.000077,3
4,pushing,loaded,start_ramp,ee_error_m,m,0.021457,0.000885,3
...,...,...,...,...,...,...,...,...
103,carrying,loaded,loaded_stationary,S_track,fraction,0.956480,0.002634,3
104,carrying,loaded,released,ee_error_m,m,0.032628,0.000379,3
105,carrying,loaded,released,planar_velocity_error_m_s,m/s,0.041866,0.000711,3
106,carrying,loaded,released,yaw_error_rad_s,rad/s,0.099266,0.001079,3
107,carrying,loaded,released,S_track,fraction,0.980345,0.003012,3

b1z1_pact_ab4_coupled_none

,profile,loading,stage,metric,unit,mean,sd,contributing_seeds
0,pushing,loaded,stationary_unloaded,ee_error_m,m,0.037825,0.000066,3
1,pushing,loaded,stationary_unloaded,planar_velocity_error_m_s,m/s,0.041120,0.000259,3
2,pushing,loaded,stationary_unloaded,yaw_error_rad_s,rad/s,0.060213,0.000791,3
3,pushing,loaded,stationary_unloaded,S_track,fraction,0.977002,0.000471,3
4,pushing,loaded,start_ramp,ee_error_m,m,0.039996,0.000224,3
...,...,...,...,...,...,...,...,...
103,carrying,loaded,loaded_stationary,S_track,fraction,0.999573,0.000739,3
104,carrying,loaded,released,ee_error_m,m,0.037005,0.000469,3
105,carrying,loaded,released,planar_velocity_error_m_s,m/s,0.027026,0.000257,3
106,carrying,loaded,released,yaw_error_rad_s,rad/s,0.070529,0.000511,3
107,carrying,loaded,released,S_track,fraction,0.937317,0.001153,3

b1z1_pact_ab5_coupled_concat

,profile,loading,stage,metric,unit,mean,sd,contributing_seeds
0,pushing,loaded,stationary_unloaded,ee_error_m,m,0.034156,0.000034,3
1,pushing,loaded,stationary_unloaded,planar_velocity_error_m_s,m/s,0.035475,0.000443,3
2,pushing,loaded,stationary_unloaded,yaw_error_rad_s,rad/s,0.054523,0.000722,3
3,pushing,loaded,stationary_unloaded,S_track,fraction,0.980179,0.000077,3
4,pushing,loaded,start_ramp,ee_error_m,m,0.045902,0.000740,3
...,...,...,...,...,...,...,...,...
103,carrying,loaded,loaded_stationary,S_track,fraction,1.000000,0.000000,3
104,carrying,loaded,released,ee_error_m,m,0.071568,0.000558,3
105,carrying,loaded,released,planar_velocity_error_m_s,m/s,0.027208,0.000165,3
106,carrying,loaded,released,yaw_error_rad_s,rad/s,0.055185,0.000448,3
107,carrying,loaded,released,S_track,fraction,0.929934,0.004318,3

b1z1_pact_ab6_position_film

,profile,loading,stage,metric,unit,mean,sd,contributing_seeds
0,pushing,loaded,stationary_unloaded,ee_error_m,m,0.080123,0.000177,3
1,pushing,loaded,stationary_unloaded,planar_velocity_error_m_s,m/s,0.031519,0.000173,3
2,pushing,loaded,stationary_unloaded,yaw_error_rad_s,rad/s,0.046000,0.001002,3
3,pushing,loaded,stationary_unloaded,S_track,fraction,0.977673,0.000431,3
4,pushing,loaded,start_ramp,ee_error_m,m,0.078756,0.000299,3
...,...,...,...,...,...,...,...,...
103,carrying,loaded,loaded_stationary,S_track,fraction,0.985813,0.001820,3
104,carrying,loaded,released,ee_error_m,m,0.082850,0.002230,3
105,carrying,loaded,released,planar_velocity_error_m_s,m/s,0.030754,0.000161,3
106,carrying,loaded,released,yaw_error_rad_s,rad/s,0.053930,0.000208,3
107,carrying,loaded,released,S_track,fraction,0.743984,0.014247,3

b1z1_pact_ab8_coupled_film

,profile,loading,stage,metric,unit,mean,sd,contributing_seeds
0,pushing,loaded,stationary_unloaded,ee_error_m,m,0.041686,0.000166,3
1,pushing,loaded,stationary_unloaded,planar_velocity_error_m_s,m/s,0.033597,0.000491,3
2,pushing,loaded,stationary_unloaded,yaw_error_rad_s,rad/s,0.058356,0.001155,3
3,pushing,loaded,stationary_unloaded,S_track,fraction,0.976868,0.000763,3
4,pushing,loaded,start_ramp,ee_error_m,m,0.049729,0.000478,3
...,...,...,...,...,...,...,...,...
103,carrying,loaded,loaded_stationary,S_track,fraction,1.000000,0.000000,3
104,carrying,loaded,released,ee_error_m,m,0.045002,0.000385,3
105,carrying,loaded,released,planar_velocity_error_m_s,m/s,0.024768,0.000244,3
106,carrying,loaded,released,yaw_error_rad_s,rad/s,0.067797,0.000646,3
107,carrying,loaded,released,S_track,fraction,0.952537,0.000280,3

b1z1_pact_ab9_representation

,profile,loading,stage,metric,unit,mean,sd,contributing_seeds
0,pushing,loaded,stationary_unloaded,ee_error_m,m,0.038939,0.000266,3
1,pushing,loaded,stationary_unloaded,planar_velocity_error_m_s,m/s,0.033599,0.000489,3
2,pushing,loaded,stationary_unloaded,yaw_error_rad_s,rad/s,0.051430,0.000434,3
3,pushing,loaded,stationary_unloaded,S_track,fraction,0.980403,0.000355,3
4,pushing,loaded,start_ramp,ee_error_m,m,0.041367,0.000231,3
...,...,...,...,...,...,...,...,...
103,carrying,loaded,loaded_stationary,S_track,fraction,1.000000,0.000000,3
104,carrying,loaded,released,ee_error_m,m,0.037536,0.000487,3
105,carrying,loaded,released,planar_velocity_error_m_s,m/s,0.025848,0.000020,3
106,carrying,loaded,released,yaw_error_rad_s,rad/s,0.067073,0.000878,3
107,carrying,loaded,released,S_track,fraction,0.975432,0.003463,3

b1z1_ppo_pos

,profile,loading,stage,metric,unit,mean,sd,contributing_seeds
0,pushing,loaded,stationary_unloaded,ee_error_m,m,0.027112,0.000216,3
1,pushing,loaded,stationary_unloaded,planar_velocity_error_m_s,m/s,0.045868,0.000239,3
2,pushing,loaded,stationary_unloaded,yaw_error_rad_s,rad/s,0.058135,0.000858,3
3,pushing,loaded,stationary_unloaded,S_track,fraction,0.980134,0.000134,3
4,pushing,loaded,start_ramp,ee_error_m,m,0.029399,0.000125,3
...,...,...,...,...,...,...,...,...
103,carrying,loaded,loaded_stationary,S_track,fraction,0.999840,0.000277,3
104,carrying,loaded,released,ee_error_m,m,0.035777,0.000289,3
105,carrying,loaded,released,planar_velocity_error_m_s,m/s,0.029325,0.000342,3
106,carrying,loaded,released,yaw_error_rad_s,rad/s,0.069653,0.000708,3
107,carrying,loaded,released,S_track,fraction,0.996574,0.001673,3

b1z1_unifp_original

,profile,loading,stage,metric,unit,mean,sd,contributing_seeds
0,pushing,loaded,stationary_unloaded,ee_error_m,m,0.023314,0.000216,3
1,pushing,loaded,stationary_unloaded,planar_velocity_error_m_s,m/s,0.028738,0.000286,3
2,pushing,loaded,stationary_unloaded,yaw_error_rad_s,rad/s,0.057995,0.000906,3
3,pushing,loaded,stationary_unloaded,S_track,fraction,0.974318,0.001218,3
4,pushing,loaded,start_ramp,ee_error_m,m,0.013971,0.000302,3
...,...,...,...,...,...,...,...,...
103,carrying,loaded,loaded_stationary,S_track,fraction,1.000000,0.000000,3
104,carrying,loaded,released,ee_error_m,m,0.025797,0.000191,3
105,carrying,loaded,released,planar_velocity_error_m_s,m/s,0.022607,0.000178,3
106,carrying,loaded,released,yaw_error_rad_s,rad/s,0.041598,0.000321,3
107,carrying,loaded,released,S_track,fraction,0.935511,0.000332,3

Portable summaries, histograms and time_series.csv require no raw recordings for comparison.